### ISSUE TITLE
Lack of License

### ISSUE THREAD

**Issue by atyler33** [kenneth-sturrock/PySkyX_ks#1]
Hey Kenneth!

I saw that you hadn't added a license to this repo and was wondering about its legal status for use in research, etc. 

Additionally, I've watched the lectures you've done over on the Astroimaging Channel, and want to thank you for your contributions to the field!

Thanks,
Alex Tyler

**Comment by kenneth-sturrock** [comment]
You can use it for anything you want, although credit is always appreciated. -Ken
