### ISSUE TITLE
Possible syntax error line 2304

### ISSUE THREAD

**Issue by storcium** [kenneth-sturrock/PySkyX_ks#3]
Hi Ken,

Did you mean to put this in line 2304:

TSXSend("sky6RASCOMTele.Abort()")

Instead of:

while TSXSend("sky6RASCOMTele.IsSlewComplete") == "0":
        if slewCount > 119:
            writeError("Mount appears stuck!")
            timeStamp("Sending abort command.")
            **sky6RASCOMTele.Abort()**
            if TSXSend("SelectedHardware.mountModel") !=  "Telescope Mount Simulator":
                time.sleep(5)
                timeStamp("Trying to stop sidereal motor.")
                TSXSend("sky6RASCOMTele.SetTracking(0, 1, 0 ,0)")
            timeStamp("Stopping script.")    
            sys.exit()
        else:
            writeNote("Slew in progress.")
            slewCount = slewCount + 1
            time.sleep(10)

**Comment by kenneth-sturrock** [comment]
Nice catch. Thanks!
